### ISSUE TITLE
Can not generate stub files when running in module

### ISSUE THREAD

**Issue by pykong** [Instagram/MonkeyType#139]
In my attempt to type annotate [copier](https://github.com/jpscaletti/copier) MonkeyType fails me.
While I can successfully create `monkeytype.sqlite3`, trying to stub or apply will fails with the following error message:

```bash
No traces found for module copier.tests.test_prompt
x traces failed to decode; use -v for details
```

Modifying the module names via SQL makes the application of the type annotations possible, however. The modification requires to strip the module name, e.g.: `copier.copier.main -> copier.main`

- **What am I doing wrong here?**
- **What could be a better way to achieve the type annotation in case of `copier`?**

Commands ran within the root level of `copier`:
1) monkeytype run `which pytest`
2) monkeytype list-modules | xargs -n1 monkeytype apply

Related: #19 #91

**Comment by carljm** [comment]
I strongly suspect that your problem is related to the existence of this file: https://github.com/jpscaletti/copier/blob/master/__init__.py

If the intended canonical import path of the modules should be like `copier.main`, then that file should not exist. It turns the outer "copier" dir (the outer directory containing the repo) into a Python package itself, thus making pytest think the code should be imported as `copier.copier.main`, which is then the path that MonkeyType sees and records.

Or if you want the canonical import paths to your modules to always include `copier.copier.` prefix (not sure why you would), then you should run the MonkeyType apply command from one directory further up, and provide module paths like `copier.copier.main` to MonkeyType.

I recommend deleting that stray `__init__.py` and trying again.

Closing because I don't believe this is a MonkeyType bug, but feel free to comment with any further question or report.
