### ISSUE TITLE
Ambiguous error when creating custom config for Django setup

### ISSUE THREAD

**Issue by danielgholmes** [Instagram/MonkeyType#141]
I'm attempting to generate stubs for some of my Django code. It's proving to be quite a challenge (so I guess this relates to #137). As per the docs, I have setup a file named `monkeytype_config.py` with the following contents:

```python
from monkeytype.config import Config
from contextlib import contextmanager
from collections import Iterator

class MyConfig(Config):
    @contextmanager
    def cli_context(self, command: str) -> Iterator[None]:
        import django
        django.setup()
        yield

CONFIG = MyConfig()
```
But when I run try any `monkeytype` command, I get the following error:

>  `monkeytype: error: argument --config/-c: invalid monkeytype_config value: 'monkeytype.config:get_default_config()'`

According to the docs:

> The default value is `monkeytype.config:get_default_config()`, which tries the config path `monkeytype_config:CONFIG` and falls back to `monkeytype.config:DefaultConfig()` if there is no `monkeytype_config` module. This allows creating a custom config that will be used by default just by creating`monkeytype_config.py` with a `CONFIG` instance in it.

I have included the appropriate file, which appears to be correct (as far as I can see), but I have no way of knowing exactly what the issue is. The message just says there is an error in the default config path without giving any details.

**Comment by carljm** [comment]
Hi @danielgholmes ! Sorry for the frustrating experience. We are using argparse argument validation to import the custom config, but I didn't realize that it totally hides the original error and replaces it with a general "invalid value" error message. I'll see if I can improve this behavior. In the meantime, I recommend simply running `python monkeytype_config.py` to see the underlying error in your config file. It seems there are two problems with it currently: 1) to use `Iterator[None]` you need `from typing import Iterator` instead of `from collections import Iterator` (the latter does not inherit `typing.Generic` and can't be subscripted), and 2) if you just want to define `cli_context` method and otherwise use the default config, you should inherit `monkeytype.config.DefaultConfig` instead of `monkeytype.config.Config`; the latter requires that you also implement `trace_store`.

Let me know if that helps! If you run into other problems, feel free to file issues.

**Comment by danielgholmes** [comment]
Thanks for your help @carljm ! It's all working.
