### ISSUE TITLE
Apply type hint for a class inside the class

### ISSUE THREAD

**Issue by tqa236** [Instagram/MonkeyType#154]
I encountered a bug (or feature?) when applying type hint to a user-defined class inside the class. I cannot find the relevant documentation to see which is the standard here, but the code doesn't work with Python 3.6, 3.7 and 3.8 on Ubuntu.

OS: Ubuntu 19.10
Python: 3.6, 3.7, 3.8
MonkeyType: 19.5.0

Here's how to reproduce the bug:

File `type_hint.py`:

```Python
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __eq__(self, other):
        return (self.x, self.y) == (other.x, other.y)
```

File `type_hint_test.py`:

```Python
import unittest

from type_hint import Point


class PointTest(unittest.TestCase):
    def test_equal(self):
        a = Point(0, 0)
        b = Point(0, 0)
        self.assertEqual(a, b)

    def test_not_equal(self):
        a = Point(0, 0)
        b = Point(0, 1)
        self.assertNotEqual(a, b)


if __name__ == "__main__":
    unittest.main()
```

Run the command:

```bash
monkeytype run type_hint_test.py
monkeytype apply type_hint
```

The formatted `type_hint.py`:

```Python
class Point:
    def __init__(self, x: int, y: int) -> None:
        self.x = x
        self.y = y

    def __eq__(self, other: Point) -> bool:
        return (self.x, self.y) == (other.x, other.y)
```

When rerun the test, I have this error:

```Python
type_hint_test.py:3: in <module>
    from type_hint import Point
type_hint.py:1: in <module>
    class Point:
type_hint.py:6: in Point
    def __eq__(self, other: Point) -> bool:
E   NameError: name 'Point' is not defined
```

What will work: double quote the `Point` class, so that the type won't load immediately

```Python
class Point:
    def __init__(self, x: int, y: int) -> None:
        self.x = x
        self.y = y

    def __eq__(self, other: "Point") -> bool:
        return (self.x, self.y) == (other.x, other.y)
```

See more here: https://stackoverflow.com/questions/44664040/type-hints-with-user-defined-classes

Relevant information:

> iirc, you can also use a string. So `def foo(bar: 'Qux')` is equivalent to `def foo(bar: Qux)` except that it does not require loading the type immediately. 

What do you think about this?

**Comment by carljm** [comment]
MonkeyType is really just a type stub generator, and uses https://github.com/ambv/retype to apply the stubs to your files directly. So if this were to be fixed, it would have to be fixed in retype. But I doubt it will be, because the future is `from __future__ import annotations`, which avoids runtime evaluation of type annotations, and renders the quotes in this case unnecessary. So my recommendation, if you are on Python 3.7, is to add `from __future__ import annotations` to your files. If you need to support earlier Python versions, you'll just need to manually update the applied annotations in such cases. MonkeyType is really intended to generate _draft_ annotations for edit and improvement by a developer; it doesn't aim to generate ready-to-run annotations in all cases.

Thanks for the report!

**Comment by tqa236** [comment]
Thank you for your help. I use Python 3.7 so that would be fine.
