### ISSUE TITLE
Help: MonkeyType doesn't collect traces for a small code sample

### ISSUE THREAD

**Issue by SimiCode** [Instagram/MonkeyType#195]
When I run the latest monkeytype with `Python 3.7.2` on this code file, it produces `No traces found for module example`, No stub, and the database table is empty.
I have tried to do this in a new virtual env, but still the same result.
I'll also note that I recently run Monkeytype on a large project and it worked fine though.

```example.py
import datetime


def get_age(yob):
    """Calculate age using date of birth.
        Args:
            yob: The year of birth.
        Returns:
            age: indicates how old the person is.
        """
    year_today = datetime.datetime.today().year
    age = year_today-yob
    return age


def calculate_bmi(weight, height):
    """Calculate body mass index.
        Args:
            wieght: in kilograms.
            height: in meters.
        Returns:
            bmi: body mass index.
    """
    bmi = weight/(height**2)
    return bmi


def main(yob, weight, height):
    """Generate the health credentials of a user based on input.
        Args:
            yob: The year of birth.
            wieght: in kilograms.
            height: in meters.
        Returns:
            age, bmi: as a dictionary.
    """
    credentials = dict(
        age=get_age(yob),
        bmi=calculate_bmi(weight, height)
    )
    return credentials


if __name__ == "__main__":
    creds = main(1993, 71, 1.79)
    print(creds)
```

**Comment by SimiCode** [comment]
Also, for wide usability, I think it would be helpful if monkeytype prints something at the end of its run or print the progress as it adds stubs to the database table; We could just provide some feedback as opposed to the current quite run.

**Comment by carljm** [comment]
Hi Edison! The cause of this problem is discussed in the documentation; MonkeyType cannot collect traces for the script you run, only for other code imported by that script. So at minimum to use MonkeyType you need at least two files: the module you actually want to collect traces for, and another script or test file which imports that module and exercises code from it.

The reason for this is that Python always sets the name of the script you run to `__main__` rather than to the name it would be imported by. We don't collect traces for `__main__` because it could be different on subsequent runs and it would be confusing to look up such traces.

**Comment by carljm** [comment]
Oh, and I would have no object to a pull request which prints some feedback about the number of traces collected at the end of a `monkeytype run`! Thanks for the suggestion!
