### ISSUE TITLE
How do I annotate pyspark project ?

### ISSUE THREAD

**Issue by eromoe** [Instagram/MonkeyType#207]
Hi,

I want to use monkeytype for my pyspark project. 

I used to debug a job by  :
```
export PYSPARK_DRIVER_PYTHON=ipython && python ./sales_forecast/src/main.py --job $action  --job-args $args
```

main.py
```

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Run a PySpark job')
    parser.add_argument('--job', type=str, required=True, dest='job_name', help="The name of the job module you want to run. (ex: poc will run job on jobs.poc package)")
    parser.add_argument('--job-args', nargs='*', help="Extra arguments to send to the PySpark job (example: --job-args template=manual-email1 foo=bar")

    spark = start_spark_session(app_name=args.job_name, master=args.master, spark_config=spark_config)

    job_module = importlib.import_module('jobs.%s' % args.job_name)
    job_module.run(spark, **job_args)

    spark.stop()
```

jobs/sample_job1.py
```
def run(spark, start_date, end_date, limit_num, **kwargs):
    do_task1(....)
    do_task2(....)
    pass

```

I want to annotate `jobs/sample_job1.py`, `do_task1`, `do_task2` ,  this function can not run without spark session .

But I don't actually can run this command in local ,  it would cost much time,  I would like early stop since it is enough to generate annotation .
Do you have any idea to support this?

**Comment by carljm** [comment]
In general it is up to you to provide a suitable process run for MonkeyType to acquire types from. This could be a test suite, or a production run, if you can configure it appropriately.

So this question really doesn't have anything to do with MonkeyType, it's a question about PySpark; how to configure your PySpark job to complete more quickly. Since I don't know anything about PySpark, unfortunately I don't have any ideas about how to do this.
