### ISSUE TITLE
Support functions decorated without functools.wraps

### ISSUE THREAD

**Issue by ntjess** [Instagram/MonkeyType#234]
Consider the following setup:

```python
# monkeymodule/file1.py
def to_str(func):
  def wrapper(*args):
    newArgs = tuple(map(str, args))
    return func(*newArgs)
  return wrapper

@to_str
def add(a, b):
  return a + b
```

```python
# monkeymodule/file2.py
from monkeymodule.file1 import add

add(1,2)
```

Terminal script:
```bash
monkeytype.exe run .\monkeymodule\file2.py
monkeytype.exe stub monkeymodule.file1
```

The output of `stubs` shows:
```python
from typing import Callable


def to_str(func: Callable) -> Callable: ...
```

Is there any way for a decorated function (in this case, `add`) to get its own type hints?

**Comment by carljm** [comment]
It looks like you'll get traces for `add` if you use `functools.wraps` to update the function returned from the decorator so that it has the qualname of the wrapped function, e.g.:

```
# monkeymodule/file1.py
from functools import wraps

def to_str(func):
  @wraps(func)
  def wrapper(*args):
    newArgs = tuple(map(str, args))
    return func(*newArgs)
  return wrapper

@to_str
def add(a, b):
  return a + b
```

I'll have to look into whether it would be possible to support this without `@wraps`.

**Comment by carljm** [comment]
Looked into this a bit, and I don't think it's really feasible for MonkeyType to support it. Given a code object and a frame, we have to be able to trace back to an importable function object. The `__wrapped__` attribute added by `functools.wraps` allows us to do this with decorated functions. It's not clear how we would do it otherwise.

I've added an FAQ entry in the docs about this. Thanks for the report!
