### ISSUE TITLE
Unit tests as workload to give to MonkeyType?

### ISSUE THREAD

**Issue by dstromberg** [Instagram/MonkeyType#240]
Am I correct in assuming that unit tests aren't really ideal for MonkeyType, because unit tests tend to feed invalid values and use mocks?

What about system tests?  Are they generally more appropriate?

**Comment by carljm** [comment]
Depends on the testing style, but yeah if a lot of mocks are used the data won't be super useful. And sure, end to end tests are more likely to give good data. The best data for MonkeyType is from "prod", whatever that means for your code base. That's not too hard for web apps, harder for distributed apps or libraries.

**Comment by robertpro** [comment]
@carljm is there a way to setup MonkeyType with a Django web server? I can't find any info like that on the docs neither on the web.

**Comment by carljm** [comment]
I don't know if there is code or documentation specifically for that available anywhere, but it's not hard to do. One approach would be to enable/disable tracing in a [Django middleware](https://docs.djangoproject.com/en/5.0/topics/http/middleware/), wrapping the call to `get_response` in MonkeyType's [tracing context manager](https://monkeytype.readthedocs.io/en/stable/tracing.html#trace-context-manager). You might want to do this randomly on only a small percentage of requests, since it will make the request a lot slower.

**Comment by robertpro** [comment]
Thanks @carljm, this is what I did based on your suggestion, leaving here in case anyone else need it.

```python
import monkeytype
from django.core.handlers.wsgi import WSGIRequest


class MonkeyTypeMiddleware:
    def __init__(self, get_response: callable) -> None:
        self.get_response = get_response

    def __call__(self, request: WSGIRequest) -> callable:
        with monkeytype.trace():
            response = self.get_response(request)

        return response
```
