### ISSUE TITLE
Add a PyTest plugin

### ISSUE THREAD

**Issue by thedrow** [Instagram/MonkeyType#25]
If monkeytype could be activated before every test run we'd be able to collect types more easily and efficiently.

**Comment by carljm** [comment]
On second thought, I think this is a reasonable idea, but I'm not sure there's any reason it needs to be distributed with monkeytype; it can be a separate project (`pytest-monkeytype` that depends on MonkeyType. Some further thoughts on the idea:

1. `monkeytype run pytest` should already offer similar functionality, but having it as a pytest plugin would certainly be more convenient, and enable more integration with e.g. pytest config. For a parallel case, you can `coverage run pytest`, but there are also pytest coverage plugins.
2. A plugin that enables monkeytype on every test run would only be useful to projects that don't measure test coverage, since monkeytype and coverage can't coexist. But it would be possible to make the plugin smarter so it can easily be turned on or off with a flag.

**Comment by samuelcolvin** [comment]
Is it possible for monkeytype to raise errors when actual types don't match annotations? 

This would be the most obvious and useful way for a pytest plugin to function.

**Comment by carljm** [comment]
@samuelcolvin Currently MonkeyType doesn't raise errors on a mismatch. You can generate a stub that ignores existing annotations using `--ignore-existing-annotations` option (or corresponding kwarg to `build_stubs_from_traces`). I suppose a hacky way would be to try to apply such a stub with retype, which would fail on any mismatch.

I'm curious what you're thinking about the purpose of the plugin, though. I assumed the purpose was to collect traces while running tests, not to verify accuracy of existing annotations.

I would like to improve MonkeyType's usefulness for verifying accuracy of existing annotations, but I'm worried that there will be a lot of false positives if this is done in an automated way (since often MonkeyType's annotations need to be hand-improved, e.g. to use less restrictive abstract or interface types instead of concrete types, to add generics or overloads, etc). So currently I don't have a better idea for this than that you run `monkeytype stub --ignore-existing-annotations` and then compare by hand.

**Comment by samuelcolvin** [comment]
@carljm thanks for the explanation. It sounds like MoneyType basically can't doesn't have a method `is_matching_type(value, type_annoation) -> bool:` which is what I was looking for.

> to verify accuracy of existing annotations

This is exactly what I was looking for. I've had a frustrating time in the past with mypy and I wanted a better way to check type annotations during testing.

pyre might be an option but I'm interested in a way of running runtime type annotations.

I build [pydantic](https://github.com/samuelcolvin/pydantic) to validated external data (eg. at an API) but a lot of people have been interested in it for internal validation (eg. at module, library, function boundaries).

Before building a pytest plugin for pydantic to validate annotations I wanted to be sure that I wasn't duplicating what MonkeyType was already doing.
