### ISSUE TITLE
document that builtin SQLiteStore doesn't support concurrent clients: `sqlite3.OperationalError: database is locked`

### ISSUE THREAD

**Issue by ColtAllen** [Instagram/MonkeyType#251]
I've been attempting to get MonkeyType 21.5.0 to work in AzureML, which uses Ubuntu VMs for compute instances. However, after multiple attempts in both Python 3.6.9 and 3.8.1, every command, version, and file I've tried returns the same error trace:

```
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/bin/monkeytype", line 8, in <module>
    sys.exit(entry_point_main())
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/monkeytype/cli.py", line 396, in entry_point_main
    sys.exit(main(sys.argv[1:], sys.stdout, sys.stderr))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/monkeytype/cli.py", line 381, in main
    handler(args, stdout, stderr)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/monkeytype/cli.py", line 210, in list_modules_handler
    modules = args.config.trace_store().list_modules()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/monkeytype/config.py", line 147, in trace_store
    return SQLiteStore.make_store(db_path)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/monkeytype/db/sqlite.py", line 82, in make_store
    create_call_trace_table(conn)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/monkeytype/db/sqlite.py", line 45, in create_call_trace_table
    conn.execute(query)
sqlite3.OperationalError: database is locked
```

The sqlite3 DB is being created, but the connection isn't being closed correctly despite the `with` statement in line 44 of  `./monkeytype/db/sqlite.py`. Is there any way to config the context manager for the sqlite DB?

**Comment by carljm** [comment]
Not sure what might be happening here, but to answer your question:

> Is there any way to config the context manager for the sqlite DB?

You can create your own call trace store per the docs at https://monkeytype.readthedocs.io/en/stable/stores.html

It can reuse code from the built-in sqlite store and override whatever you like.

If you are able to trace this down to a bug that is fixable in the built-in sqlite store, please report back your findings!

**Comment by ColtAllen** [comment]
I've had a chance to revisit this, and I'm certain this is due to a bug in the `monkeytype.db.sqlite.create_call_trace_table` method:
https://github.com/Instagram/MonkeyType/blame/main/monkeytype/db/sqlite.py#L35

The connection object being called by the `with` statement in line 35 needs to be closed manually, per the docs:
https://docs.python.org/3.8/library/sqlite3.html#using-the-connection-as-a-context-manager

Here's a blog post providing more information:
https://blog.rtwilson.com/a-python-sqlite3-context-manager-gotcha/

Is it standard practice to create proprietary call trace stores? This is such a simple bug (and easy fix) that it blows my mind it hasn't come up yet.

**Comment by carljm** [comment]
Thanks for the additional analysis! I understand the behavior of `with conn:` but I don't think that means there is a bug in MonkeyType. That SQLite connection is not just used there on line 35 to create the table, it is intentionally kept open by the `CallTraceStore`, and needs to be used throughout the life of the process to store traces to the sqlite db. So it's intentional and necessary that that connection is not closed until process shutdown. This clearly works fine in the simple common case of running a single process under MonkeyType tracing, since many people do that with the default call trace store.

It seems like in your scenario somehow you have multiple processes active at once trying to write to the same SQLite db. This doesn't work; it's a fundamental limitation of SQLite. In such scenarios the right thing to do would be to write your own call trace store that writes to a database that supports multiple concurrent clients (i.e. something like MySQL or PostgreSQL.)

**Comment by carljm** [comment]
I'm going to keep this issue open as a documentation issue -- the docs should be clearer that the default call trace store, since it uses SQLite, doesn't support multiple concurrent clients.

**Comment by ColtAllen** [comment]
@carljm Thanks! That was helpful. Now I'm wondering why I'm inadvertently trigger multiple processes. I did some digging into `monkeytype.cli.py` and found the following:

https://github.com/Instagram/MonkeyType/blame/main/monkeytype/cli.py#L224
`modules = args.config.trace_store().list_modules()`

https://github.com/Instagram/MonkeyType/blame/main/monkeytype/cli.py#L246
`args.limit = args.config.query_limit()`

I'm not that familiar with the `argparse` library (I much prefer `click`) but do you think these attribute methods could be the culprits if attempting to write to an Ubuntu filepath accessible by multiple users?

I'm using `MonkeyPatch` on AzureML, where compute instances are user-specific. Although `MonkeyPatch` is ran from an isolated compute instance, the `sqlite3` trace store is written to the shared AzureML file system. I'd imagine the vast majority of `MonkeyPatch` users have a wildly different dev environment setup, but this nonetheless could be a bug/limitation for enterprise users working in environments set up for teams.

**Comment by carljm** [comment]
Multiple processes is one possibility, but if you're just doing a simple run (can you show the exact command line and config you are using?) I guess there are other possibilities maybe, like bad interactions of some kind between SQLite and the AzureML filesystem implementation.

Could you try writing a very simple Python script that opens a connection to a SQLite database file located on the AzureML filesystem, and see if that works?

Can you try deleting the SQLite database file MonkeyType is trying to use, to see if it maybe got left in a bad state and just clearing it out resolves the problem?

**Comment by ColtAllen** [comment]
@carljm  I'm just running the basic `monkeytype run script.py` command.

It turns out even executing a simple `sqlite3.connect('path/to/db')` will raise a locked DB  exception in AzureML. I found a Stack Overflow question explaining why this happens on Azure App Services:

https://stackoverflow.com/questions/53226642/sqlite3-database-is-locked-in-azure

I'm closing this issue as the solution involves Azure configurations that are beyond the scope of `MonkeyPatch`. AzureML is mainly geared towards entry-level data scientists, and this isn't the first time I've encountered limitations using it.

**Comment by carljm** [comment]
If it's not actually a concurrency issue but an AzureML specific issue, I'll go ahead and close this; we'll document the concurrency thing if someone actually runs into it, since that will give a much better idea of the circumstances that might lead someone to hit this due to concurrency, which will let us document it better. Thanks for reporting back on the results of your research.

Sorry you found the MonkeyType documentation difficult to understand. Not sure that's actionable feedback in a general sense: I'm not sure how one can write documentation for a technical tool intended for use by programmers without using technical language. But if there are specific areas of the documentation that you found particularly hard to understand, file an issue with specific pointers and I'll be happy to look into clarifying/simplifying/expanding!
