### ISSUE TITLE
Understanding typing.get_type for dicts with string keys

### ISSUE THREAD

**Issue by dbieber** [Instagram/MonkeyType#262]
Hi there, I'm interested in using monkeytype to identify types of values including collections.
I tried the follow simple examples to see if monkeytype would work for what I'm looking for, and was surprised to see some of its behavior.

```python
from monkeytype import typing

typing.get_type({1:2, 'q': 4}, 10)
# typing.Dict[typing.Union[int, str], int]  # Worked as intended

typing.get_type({'1': 2, 'q': 4}, 10)
# monkeytype.typing.DUMMY_NAME  # Was expecting typing.Dict[str, int] 
typing.get_dict_type({'1': 2, 'q': 4}, 10)
# monkeytype.typing.DUMMY_NAME  # Was expecting typing.Dict[str, int] 
```

Can you point me in the right direction for understanding what's going on with DUMMY_NAME and why it isn't producing Dict[str, int]  like I expected it would? Is there a function like get_type that has the behavior of producing a type annotation for the provided value (including for dicts with string keys)?

(Still poking around the repo and learning about the project, so forgive me if I asked this question prematurely.)

**Comment by carljm** [comment]
MonkeyType supports creating new TypedDict types for more precise typing of dictionaries that are used as "cheap objects" (i.e. heterogenous value types, with value type per well-known key name.) See https://mypy.readthedocs.io/en/stable/more_types.html#typeddict

Since Python doesn't have syntax to describe an anonymous TypedDict type "inline," all TypedDicts must be named types. This is the problem that `DUMMY_NAME` solves; we initially just use a dummy name for the typed dict type, and then when we are actually emitting annotations we'll give it a name, emit its definition, and use that name in the annotation.

I think the return value from `get_type` in the second two cases there should be a `typing.TypedDict` object, whose `__annotations__` attribute you should be able to introspect to get the types of all fields.

The heuristics for deciding when to return a normal homogenous `Dict` type vs a `TypedDict` are: return a `TypedDict` if all strings are keys and the number of keys is less than or equal to `max_typed_dict_size` (the second argument to `get_type`). If you don't want to deal with the complexity of `TypedDict` types, you can get the behavior you expected above by simply passing `0` as the second argument to `get_type`.

**Comment by carljm** [comment]
It might be worth considering adding a heuristic to _not_ ever infer a `TypedDict` if the dict values are all the same type...
