### ISSUE TITLE
Feature Request: support pytest-xdist parallelism

### ISSUE THREAD

**Issue by johnarnold** [Instagram/MonkeyType#62]
Use Case: For projects with many tests and/or long-running tests it can take an extreme amount of time to generate all the traces serially.   Pytest-xdist can be used to run tests in parallel processes. If there was a way to hook the tracer in to all the tests, that would really speed up the process.

Possible implementation;  pytest-monkeytest plugin?  Support enabling tracing in conftest.py?

**Comment by carljm** [comment]
This is a great idea. I think it belongs in a pytest-monkeytype plugin (and you’re the second person to file an issue mentioning the idea; see #25.) Because pytest plugins are enabled by installation, we won’t bundle such a plugin with monkeytype itself; it should be separately distributed. 

Also, we (monkeytype maintainers) are not likely to create such a plugin ourselves, though we are happy to provide some advice/consultation/pointers on the implementation as needed. 

For those reasons, I’m closing this issue on monkeytype since it’s not actionable for this repo.

**Comment by carljm** [comment]
Also, if there are changes to the monkeytype api needed to support the implementation of the plugin, we’d happliy consider those as specific feature requests.
